### ISSUE TITLE
64x32 Panel Skips Every Other Line

### ISSUE THREAD

**Issue by tlewiscpp** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#104]
Hey,

I have a [NodeMCU-32S](https://www.amazon.com/gp/product/B086MGH7JV/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1) that I have connected with the default wiring to a [64x32 panel](https://www.amazon.com/gp/product/B07SDMWX9R/ref=ppx_yo_dt_b_asin_title_o01_s01?ie=UTF8&psc=1). I have tried both the PlatformIO test patterns and my own code and they all repeat every other row. Any idea what would be causing this?

[PlatformIO Test Patterns](https://youtu.be/2NdEHodTv0g)

[One-by-one example](https://youtu.be/qinPm0CGb9c)

Code for the one-by-one example (simplified):

```
#include <Arduino.h>
#include <ESP32-HUB75-MatrixPanel-I2S-DMA.h>

MatrixPanel_I2S_DMA *dmaDisplay{new MatrixPanel_I2S_DMA{}};

void setup() {
    dmaDisplay->begin();

    //RGB
    dmaDisplay->fillScreen(dmaDisplay->color565(255,0,0));
    delay(750);
    dmaDisplay->fillScreen(dmaDisplay->color565(0,255,0));
    delay(750);
    dmaDisplay->fillScreen(dmaDisplay->color565(0,0,255));
    delay(750);

    //Clear display
    dmaDisplay->fillScreen(dmaDisplay->color565(0,0,0));
    delay(750);
}

static int column{0};
static int row{0};

void loop() {
    Serial.print("Drawing column "); Serial.print(column); Serial.print(", row "); Serial.println(row);
    dmaDisplay->drawPixel(column,row, dmaDisplay->color565(255,255,255));
    column++;
    if (column >= MODULE_WIDTH) {
      column = 0;
      row++;
    }
    if (row >= MODULE_HEIGHT) {
        row = 0;
        column = 0;
    }
    delay(15);
}

**Comment by mrfaptastic** [comment]
You've wired it wrong or have a wire issue. Probably 'b' pin.
