### ISSUE TITLE
I2S audio

### ISSUE THREAD

**Issue by dmb-220** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#106]
hello,
 can i2S audio be used?
https://github.com/schreibfaul1/ESP32-audioI2S
do you need any change? pin change understandable.
internet radio project, with rgb led matrix.

**Comment by mrfaptastic** [comment]
Unlikely.  Not enough spare gpios.

**Comment by dmb-220** [comment]
#define R1_PIN_DEFAULT  2
#define G1_PIN_DEFAULT  4
#define B1_PIN_DEFAULT  5
#define R2_PIN_DEFAULT  14
#define G2_PIN_DEFAULT  13
#define B2_PIN_DEFAULT  12

#define A_PIN_DEFAULT   23
#define B_PIN_DEFAULT   19
#define C_PIN_DEFAULT   17
#define D_PIN_DEFAULT   32
#define E_PIN_DEFAULT   33 
          
#define LAT_PIN_DEFAULT 18
#define OE_PIN_DEFAULT  15
#define CLK_PIN_DEFAULT 16

SPI I will not use, 

I2S 25, 26, 27 pins, web radio.

+i2c pins, get temperature, humidity.

interesings i2S audio works?

**Comment by mrfaptastic** [comment]
You will have to experiment to find out if it works.

**Comment by mrfaptastic** [comment]
If you actually have enough GPIO, I don’t see why that wouldn’t work. ESP32 will need to use I2S0 because this library uses I2S1. You should contact the developers of audioI2S for any other questions.

**Comment by mrweaver** [comment]
That actually may work out well if there is an intention for using the DACs to output the audio.

According the [documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/i2s.html):
> I2S0 output can be routed directly to the digital-to-analog converter’s (DAC) output channels (GPIO 25 & GPIO 26) to produce direct analog output without involving any external I2S codecs. I2S0 can also be used for transmitting PDM (Pulse-density modulation) signals.

**Comment by marianomd** [comment]
I'm trying this and it's not working. Using esphome I2S audio. I'm not sure if ESP32 allows two independent DMA transfers simultaneusly. Will report if I make any progress.

**Comment by mrfaptastic** [comment]
It should. Try lowering the clock speed of the hub 75 output. Could be memory bandwidth related.

**Comment by marianomd** [comment]
Also this:

![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/274989/190126bb-8f1b-433d-bb5f-3d077143db56)

https://www.youtube.com/watch?v=6PGrsZmYAJ0
