### ISSUE TITLE
 Error compiling ESP32 Wrover module card and others.

### ISSUE THREAD

**Issue by GMDionicio** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#108]
Hello, I appreciate if you help me with this problem. Download this library as an option. zip but it doesn't compile for any ESP 32 board, I have the adifruit_GFX and Fastled.h libraries updated to the latest version. this is the error i have:

![Screenshot_3](https://user-images.githubusercontent.com/81241932/113166473-69f52800-9208-11eb-8823-ae549525fae1.jpg)

Arduino:1.8.13 (Windows 10), Tarjeta:"ESP32 Wrover Module, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), QIO, 80MHz, 921600, None"

In file included from C:\Users\DAVIDO~1\AppData\Local\Temp\arduino_modified_sketch_156257\ChainedPanelsAuroraDemo.ino:61:0:

C:\Users\David Olaya\Documents\Arduino\libraries\ESP32-HUB75-MatrixPanel-I2S-DMA-master/ESP32-VirtualMatrixPanel-I2S-DMA.h:77:47: error: 'RGB24' has not been declared

     void drawPixelRGB24(int16_t x, int16_t y, RGB24 color);

                                               ^

C:\Users\David Olaya\Documents\Arduino\libraries\ESP32-HUB75-MatrixPanel-I2S-DMA-master/ESP32-VirtualMatrixPanel-I2S-DMA.h: In member function 'void VirtualMatrixPanel::drawPixelRGB565(int16_t, int16_t, uint16_t)':

C:\Users\David Olaya\Documents\Arduino\libraries\ESP32-HUB75-MatrixPanel-I2S-DMA-master/ESP32-VirtualMatrixPanel-I2S-DMA.h:162:18: error: 'class MatrixPanel_I2S_DMA' has no member named 'drawPixelRGB565'

   this->display->drawPixelRGB565( coords.x, coords.y, color);

                 ^

C:\Users\David Olaya\Documents\Arduino\libraries\ESP32-HUB75-MatrixPanel-I2S-DMA-master/ESP32-VirtualMatrixPanel-I2S-DMA.h: At global scope:

C:\Users\David Olaya\Documents\Arduino\libraries\ESP32-HUB75-MatrixPanel-I2S-DMA-master/ESP32-VirtualMatrixPanel-I2S-DMA.h:172:70: error: 'RGB24' has not been declared

 inline void VirtualMatrixPanel::drawPixelRGB24(int16_t x, int16_t y, RGB24 color)

                                                                      ^

C:\Users\David Olaya\Documents\Arduino\libraries\ESP32-HUB75-MatrixPanel-I2S-DMA-master/ESP32-VirtualMatrixPanel-I2S-DMA.h: In member function 'void VirtualMatrixPanel::drawPixelRGB24(int16_t, int16_t, int)':

C:\Users\David Olaya\Documents\Arduino\libraries\ESP32-HUB75-MatrixPanel-I2S-DMA-master/ESP32-VirtualMatrixPanel-I2S-DMA.h:175:18: error: 'class MatrixPanel_I2S_DMA' has no member named 'drawPixelRGB24'

   this->display->drawPixelRGB24(coords.x, coords.y, color);

                  ^

In file included from C:\Users\DAVIDO~1\AppData\Local\Temp\arduino_modified_sketch_156257\ChainedPanelsAuroraDemo.ino:62:0:

C:\Users\David Olaya\Documents\Arduino\libraries\FastLED-master\src/FastLED.h: At global scope:

C:\Users\David Olaya\Documents\Arduino\libraries\FastLED-master\src/FastLED.h:14:21: note: #pragma message: FastLED version 3.004.000

 #    pragma message "FastLED version 3.004.000"

                     ^

In file included from C:\Users\David Olaya\Documents\Arduino\libraries\FastLED-master\src/FastLED.h:65:0,

                 from C:\Users\DAVIDO~1\AppData\Local\Temp\arduino_modified_sketch_156257\ChainedPanelsAuroraDemo.ino:62:

C:\Users\David Olaya\Documents\Arduino\libraries\FastLED-master\src/fastspi.h:140:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

exit status 1

Error compilando para la tarjeta ESP32 Wrover Module.

Este informe podría contener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

**Comment by csloz** [comment]
Looks like this recent commit removed the RGB24 define.

https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/commit/51345ec0ac133b3c3c6816fdda8d66d029290487 <https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/commit/51345ec0ac133b3c3c6816fdda8d66d029290487>


Notes say - Remove legacy RGB24 struct, and overide drawPixel to support CRGB 24bit struct value passed as a colour. FastLED library required to be installed when FASTLED_CRGB_SUPPORT enabled.


Suggest revert that change and try again.
Or define it manually - i.e.


 

typedef struct RGB24 {
    RGB24() : RGB24(0,0,0) {}
    RGB24(uint8_t r, uint8_t g, uint8_t b) {
        red = r; green = g; blue = b;
    }
    RGB24& operator=(const RGB24& col);

    uint8_t red;
    uint8_t green;
    uint8_t blue;
} RGB24;

**Comment by mrfaptastic** [comment]
Use version 2.0.1 for now, I'll have to make some further changes to the examples to fix them up as well.

**Comment by GMDionicio** [comment]
> Use la versión 2.0.1 por ahora, tendré que hacer algunos cambios adicionales en los ejemplos para arreglarlos y veo que el problema está en los ejemplos de encadenamiento.



Hi, I already downloaded version 2.0.1 and compiled it, but none of the examples work on the matrix. This is what the IDE shows me after compiling:

![Screenshot_4](https://user-images.githubusercontent.com/81241932/113217260-48656200-9243-11eb-9a2c-b04815531c0c.jpg)

In file included from C:\Users\David Olaya\Documents\Arduino\libraries\ESP32_HUB75_LED_MATRIX_PANEL_DMA_Display\examples\ChainedPanelsAuroraDemo\ChainedPanelsAuroraDemo.ino:58:0:
C:\Users\David Olaya\Documents\Arduino\libraries\FastLED-master\src/FastLED.h:14:21: note: #pragma message: FastLED version 3.004.000
 #    pragma message "FastLED version 3.004.000"
                     ^
In file included from C:\Users\David Olaya\Documents\Arduino\libraries\FastLED-master\src/FastLED.h:65:0,
                 from C:\Users\David Olaya\Documents\Arduino\libraries\ESP32_HUB75_LED_MATRIX_PANEL_DMA_Display\examples\ChainedPanelsAuroraDemo\ChainedPanelsAuroraDemo.ino:58:
C:\Users\David Olaya\Documents\Arduino\libraries\FastLED-master\src/fastspi.h:140:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^
El Sketch usa 319437 bytes (24%) del espacio de almacenamiento de programa. El máximo es 1310720 bytes.
Las variables Globales usan 46460 bytes (14%) de la memoria dinámica, dejando 281220 bytes para las variables locales. El máximo es 327680 bytes.
esptool.py v2.6
Serial port COM3
Connecting........__
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, Coding Scheme None
MAC: 30:ae:a4:24:02:80
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 8192 bytes to 47...
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 3120.8 kbit/s)...
Hash of data verified.
Compressed 17392 bytes to 11186...
Wrote 17392 bytes (11186 compressed) at 0x00001000 in 0.5 seconds (effective 271.2 kbit/s)...
Hash of data verified.
Compressed 319552 bytes to 155627...
Wrote 319552 bytes (155627 compressed) at 0x00010000 in 7.2 seconds (effective 356.3 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 128...
Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.0 seconds (effective 1536.0 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...




![Screenshot_6](https://user-images.githubusercontent.com/81241932/113217446-967a6580-9243-11eb-8e32-2f665c934a21.jpg)
 


finally the matrix does not show anything.
![WhatsApp Image 2021-03-31 at 5 08 17 PM](https://user-images.githubusercontent.com/81241932/113217977-5cf62a00-9244-11eb-87ab-bf4f8bc17dd5.jpeg)

**Comment by mrfaptastic** [comment]
Can you start with the simpletestshapes example first? From what you have
provided it looks like it has compiled and is running correctly in the
esp32.

The issue is likely wiring or power

**Comment by GMDionicio** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/81241932/113219597-4b625180-9247-11eb-8229-a47b74af8c5c.jpg)





This library is very good and it is not the first time that I use it since I have been working with it for 15 days, the problem arose when I updated ESP32-HUB75-MatrixPanel-I2S-DMA since it did not work again. The pins that I have connected are by default as indicated in the library and the power supply is from a 5v 31 Amp computer.

**Comment by mrfaptastic** [comment]
What version of this library worked  before it stopped working?

**Comment by GMDionicio** [comment]
As I mentioned before, download the library through the page https://github.com/ I did not look at the version, I only know that since March 29, 2021 I downloaded the library again through the page and from that moment the matrix I do not work. I first encountered the problem with the build of the boards.

**Comment by csloz** [comment]
The flash read error is the likely issue.  Your flash is bad.  Try another chip.

**Comment by mrfaptastic** [comment]
@csloz - Good pick up, didn't look close enough at the screenshot. Looks like the ESP32's flash chip is cactus.
