### ISSUE TITLE
'class MatrixPanel_I2S_DMA' has no member named 'drawPixelRGB565'

### ISSUE THREAD

**Issue by FrancesDK** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#113]
Hello,
I'm using ESP32 and 64x64LedPanel

In the AnimatedGIFPanel exemple I'm getting this error while compiling
All other examples works well.

Can anyone explain to me what am I going wrong?
Thank you

C:\Users\wwwru\AppData\Local\Temp\arduino_modified_sketch_717407\AnimatedGIFPanel.ino: In function 'void GIFDraw(GIFDRAW*)':
AnimatedGIFPanel:98:14: error: 'class MatrixPanel_I2S_DMA' has no member named 'drawPixelRGB565'
  dma_display.drawPixelRGB565(x + xOffset, y, usTemp[xOffset]);
              ^
AnimatedGIFPanel:126:14: error: 'class MatrixPanel_I2S_DMA' has no member named 'drawPixelRGB565'
  dma_display.drawPixelRGB565(x, y, usPalette[*s++])
exit status 1
'class MatrixPanel_I2S_DMA' has no member named 'drawPixelRGB565'
![Capture](https://user-images.githubusercontent.com/80853920/114314191-fb627500-9af9-11eb-8b66-eb837e6f09b4.PNG)

**Comment by mrfaptastic** [comment]
Change the name of the function called to 'drawPixel'.

I'll have to update the example.

**Comment by FrancesDK** [comment]
> 
> 
> Change the name of the function called to 'drawPixel'.
> 
> I'll have to update the example.

Thank you or your quick reply and great work Sir,
It's working now
