### ISSUE TITLE
Is the PCB design file available?

### ISSUE THREAD

**Issue by windoze** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#125]
I'm living in a region that Tindie cannot ship to, so I'm thinking about make the PCB by myself, but I cannot find the doc/schema in this repo.
Am I looking at the wrong place?

Thanks for any info.

**Comment by mrfaptastic** [comment]
Please read the README. There are links there to other people's designs.

**Comment by windoze** [comment]
Thanks for the note.

Regards,
Chen
