### ISSUE TITLE
2.0.5 - 64x32 - lower left leds shifted

### ISSUE THREAD

**Issue by Daedelos** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#133]
With 2.0.5 on my 64x32 leds appear to be shifted in the lower left quarter of the panel. e.g.

display.writeFastVLine(17, 0, display.height(), display.color565(0, 0, 255));

results in a broken vertical line in the lower potion of my 64x32 panel.

2.0.3 works correctly with no broken line (shifted leds)

![IMG_20210612_104747](https://user-images.githubusercontent.com/25985496/121772262-3883cb80-cb6c-11eb-9560-276a90f84bf0.jpg)

![IMG_20210611_231800](https://user-images.githubusercontent.com/25985496/121772327-a7f9bb00-cb6c-11eb-9ce8-794506d248de.jpg)

**Comment by mrfaptastic** [comment]
Is this one panel or a chain of panels? I can't tell.

Are you using the virtual display class. If so, post the sketch code.

Finally, can you reverse what I did in #130 to see if this is a clockphase problem that I've introduced.

**Comment by Daedelos** [comment]
Single panel.
Not using the virtual display class. 

I changed the clockphase to false and the line is drawn correctly.

**Comment by mrfaptastic** [comment]
Good to know it's fixed. There are too many permutations of these panels now... can't seem to fix an issue without breaking another.

Can you tell me what the chipset your panels are?

**Comment by Daedelos** [comment]
ICN2028AP / ICN2012

![IMG_20210612_125701](https://user-images.githubusercontent.com/25985496/121776330-27df4f80-cb84-11eb-9fd7-e7cc8b64779f.jpg)

**Comment by vortigont** [comment]
> There are too many permutations of these panels now... can't seem to fix an issue without breaking another.

Looks like we might need some kind of "config templates" or maybe a WiKi table with confirmed settings

**Comment by mrfaptastic** [comment]
We could, but that's another thing we'd have to keep up to date constantly. I'd perfer users of the library to experiment a bit - what I will do is raise an issue of 'common issue' and pin it to the top - give people guidance.
