### ISSUE TITLE
how can i use small size text on chained panels?

### ISSUE THREAD

**Issue by zeroxxx88** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#135]
hello!

I use two 64x32 panels chained,everything is ok,but set text size 1 is 17 pixels high,how can i use 8 pixels high text?thank you!

**Comment by mrfaptastic** [comment]
This is an AdafruitGFX library question, but my understanding is that the default monospace (no font loaded) font is 8x8px.
