### ISSUE TITLE
Gif animation with double buffer support

### ISSUE THREAD

**Issue by tsctrl** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#136]
Hi @mrfaptastic,

i did some testing to run the GifAnimator example using the double buffer, i simply put buffer swap at start and the end of  the pixel mapper GIFDraw but experience leggy and flickering gif animation.

1. how to enable double buffer for gif animation, if possible from the example sketch?
2. i guess the pixel written in the front buffer as long as no swap triggered for double buffer setup. is this the approach or is there workaround or better suggestion on running the gif files since double buffer was enabled?

Thanks @mrfaptastic !

**Comment by mrfaptastic** [comment]
This isn't an issue of this library. Larry's GIF Decoder can call GIFDraw arbitrarily and doesn't get called only once per frame.
