### ISSUE TITLE
Flick

### ISSUE THREAD

**Issue by subashsaraf** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#144]
I made a clock with this Library actually the code  was from Great Project RGB clock I modify the code according to your Lib. Hence I face Flickering issue . Where the code is absolutely  fine PxMatrix lib but when I use "ESP32-HUB75-MatrixPanel-I2S-DMA" then the display is become Flickering .So is there any other way to solve the problem

Link To See the Flickering Issue

https://youtu.be/rzNrKGc8oXI

Code :- 

[Esp32_DS1307_DHT11_Matrix_p4_RGB_64x32_DMA_AMPM_dma_display.zip](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/files/6763764/Esp32_DS1307_DHT11_Matrix_p4_RGB_64x32_DMA_AMPM_dma_display.zip)

**Comment by mrfaptastic** [comment]
What was the issue?
