### ISSUE TITLE
 Flickering Issue with "ESP32-HUB75-MatrixPanel-I2S-DMA" only

### ISSUE THREAD

**Issue by subashsaraf** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#145]
I made a clock with this Library actually the code was from Great Project RGB clock I modify the code according to your Lib. Hence I face Flickering issue . Where the code is absolutely fine PxMatrix lib but when I use "ESP32-HUB75-MatrixPanel-I2S-DMA" then the display is become Flickering .So is there any other way to solve the problem

Link To See the Flickering Issue

https://youtu.be/rzNrKGc8oXI

Code :-

Esp32_DS1307_DHT11_Matrix_p4_RGB_64x32_DMA_AMPM_dma_display.zip
[Esp32_DS1307_DHT11_Matrix_p4_RGB_64x32_DMA_AMPM_dma_display.zip](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/files/6763779/Esp32_DS1307_DHT11_Matrix_p4_RGB_64x32_DMA_AMPM_dma_display.zip)

subashsaraf@gmail.com

**Comment by mrfaptastic** [comment]
Turn off your LDR checking code and see if that fixes the issues. I think you have conflicting pin mappings causing noise on the DMA output.

**Comment by subashsaraf** [comment]
Thanks for reply,

        I  check everything is correct. I attached the full scratch for
your knowledge. I attached the LDR pin to 34 the pin in mint for input only
and all pins are mapped according to the DMA library. So kindly find the
attached file for the

same


Subash Saraf
M: +91 9437357170
Email : ***@***.***

**Comment by mrfaptastic** [comment]
What does SimpleTestShapes example look like?

**Comment by subashsaraf** [comment]
Kindly Scc the video

Subash Saraf
Manager (WRM E&A)
M: +91 9437357170
Email : ***@***.***
             ***@***.***
BHUSHAN POWER & STEEL LIMITED
Vill: Thelkuli | P.O.: Lapanga | Tehshil : Rengali
Distt.: Sambalpur – 768232 | State : Orissa (INDIA)

**Comment by mrfaptastic** [comment]
https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/tree/master/examples/1_SimpleTestShapes

?

**Comment by mrfaptastic** [comment]
Try: https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/tree/master/examples/1_SimpleTestShapes

Take a video of this sketch

**Comment by subashsaraf** [comment]
Sir,
I already checked this this work fine. But in case  scrolling text the
flickering happen. This code is absolutely fine in pxmatrix

Subash Saraf
Manager (WRM E&A)
M: +91 9437357170
Email : ***@***.***
             ***@***.***
BHUSHAN POWER & STEEL LIMITED
Vill: Thelkuli | P.O.: Lapanga | Tehshil : Rengali
Distt.: Sambalpur – 768232 | State : Orissa (INDIA)

**Comment by 2BECKHAM2** [comment]
@mrfaptastic.

Many thanks for the excellent library.

I'm facing some noise/flickering issues with the 64x32 panel with 1.0.6 esp32 version. I have connected a 3300uf capacitor across  5v in the panel.

https://drive.google.com/drive/folders/1c6tXlEqq_mQJvfQCB-mob6V1B1d418zN?usp=sharing

![IMG_20210722_201736](https://user-images.githubusercontent.com/10421932/126660174-b746db57-6ce9-47cc-b038-f7e65fd45947.jpg)

![IMG_20210722_144234 1](https://user-images.githubusercontent.com/10421932/126660182-6dcd4152-27a3-4109-b152-e08b36ec9a99.jpg)


Is there any config changes that I would have to make.

Thanks.

**Comment by mrfaptastic** [comment]
Can you check that non-GND pins are not going to ground.

Can you draw a single diagonal line as well? 
Looks like some address line issue, check the A,B,C,D pin mapping - perhaps the pins may have moved? Who knows. There seems to be a few of these issues being raised recently.

![RGB_HUB75_PINS](https://user-images.githubusercontent.com/12006953/126665051-c88043ff-1f32-48c5-9d39-cfa0e00407b4.png)

**Comment by 2BECKHAM2** [comment]
Thanks for the quick response.

Can you please share me the pin mapping details for ESP 32.

I don't have any clue on DR1, DB1, DR2, DB2, A, C OE, DG1DG2 B, D  and LAT
at the ESP 32 Side.

Sorry to bother you.

Thanks in advance.

**Comment by mrfaptastic** [comment]
How have you connected the ESP32 to the LED panel? With some custom PCB or pin-by-pin with jumper cable.

You need to check your wiring.

**Comment by 2BECKHAM2** [comment]
I have not used any custom pcb. Connected one by one as mentioned by you in
the GitHub page link.

**Comment by mrfaptastic** [comment]
Looking at your photo I see a 16 wire ribbon cable connecting to the panel. So how do you do that without a pcb?

There's something wrong be with your wiring. You need to keep the wire length between the esp32 and panel as short as possible, like 4-5 inches max, or these issues will occur.

This is an electrical issue I think.

**Comment by 2BECKHAM2** [comment]
From the ribbon cable, I have used male to female jumper wire ( colored one which normally use for the esp project) female end will be connected to esp 32.


Find attached screenshot for reference.

![IMG_20210723_021123.jpg](https://user-images.githubusercontent.com/10421932/126708026-0fbe5667-1413-436b-bd00-36694a1d0157.jpg)


![IMG_20210723_021110.jpg](https://user-images.githubusercontent.com/10421932/126708086-c1dddd49-abcf-4642-b1cb-19e68d95ff85.jpg)

Thanks in advance.

**Comment by mrfaptastic** [comment]
That's likely your problem then. Use shorter female to female jumper cables and connecting directly to the LED panel.

**Comment by mrfaptastic** [comment]
Also ensure ground pins on LED panel are grounded.

**Comment by 2BECKHAM2** [comment]
Thanks for your help. Will check as suggested and up date.

**Comment by 2BECKHAM2** [comment]
@mrfaptastic ,

I  have connected the shorter cables and observed the less flickering and noise. Find below for your reference.

[https://drive.google.com/file/d/1nw4ysHyfHBCSnwHW25mCvjpaQzlTfraj/view?usp=sharing](url)

[https://drive.google.com/file/d/1bRwCGyKM6wTf2oT20CQ6o0N3jbupVB9X/view?usp=sharing](url)

![IMG_20210723_201121](https://user-images.githubusercontent.com/10421932/126802033-7cdfdbb4-cb45-45e8-a537-f3154399e6c4.jpg)



Also regarding the latch blanking configuration, where exactly should I be making the necessary code changes?

Thanks.

**Comment by mrfaptastic** [comment]
In the mxconfig that you pass to the library. Refer to: https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/issues/134

**Comment by 2BECKHAM2** [comment]
@mrfaptastic 

Can you please help me in which file the below configuration needs to be changed.

mxconfig.latch_blanking = 4;
mxconfig.i2sspeed = HUB75_I2S_CFG::HZ_10M;

//and reduce brightness as well

// let's adjust default brightness to about 50%
dma_display->setBrightness8(128);    // range is 0-255, 0 - 0%, 255 - 100%

mx_config.clkphase = false;

Thanks in advance.

**Comment by mrfaptastic** [comment]
Please look at the source code of the other examples.

**Comment by 2BECKHAM2** [comment]
Its working like a charm after doing the config changes. - Thanks a lot for your help.

![IMG_20210724_193117](https://user-images.githubusercontent.com/10421932/126870999-00d20443-048e-4f2b-937a-6a8d4b2b9d46.jpg)
![IMG_20210724_193120](https://user-images.githubusercontent.com/10421932/126871004-7786813f-568d-470e-938e-12e29b68d2ea.jpg)
![IMG_20210724_193122](https://user-images.githubusercontent.com/10421932/126871006-273d1dda-99c5-4d14-9d06-687ddf1586c2.jpg)
![IMG_20210724_193112](https://user-images.githubusercontent.com/10421932/126871007-7d8270a8-8a52-48b4-9a82-cb45c633ef97.jpg)
![IMG_20210724_193116](https://user-images.githubusercontent.com/10421932/126871009-3d81132a-e631-49b6-bb5c-e845abe68582.jpg)

**Comment by subashsaraf** [comment]
> 
> 
> Its working like a charm after doing the config changes. - Thanks a lot for your help.
> 
> ![IMG_20210724_193117](https://user-images.githubusercontent.com/10421932/126870999-00d20443-048e-4f2b-937a-6a8d4b2b9d46.jpg)
> ![IMG_20210724_193120](https://user-images.githubusercontent.com/10421932/126871004-7786813f-568d-470e-938e-12e29b68d2ea.jpg)
> ![IMG_20210724_193122](https://user-images.githubusercontent.com/10421932/126871006-273d1dda-99c5-4d14-9d06-687ddf1586c2.jpg)
> ![IMG_20210724_193112](https://user-images.githubusercontent.com/10421932/126871007-7d8270a8-8a52-48b4-9a82-cb45c633ef97.jpg)
> ![IMG_20210724_193116](https://user-images.githubusercontent.com/10421932/126871009-3d81132a-e631-49b6-bb5c-e845abe68582.jpg)

Sir,
     Can you please post the the code link which you is  working fine without any issue  .So that I will correction my code according to your program 

Subashsaraf@gmail.com

**Comment by subashsaraf** [comment]
> 
> 
> > Its working like a charm after doing the config changes. - Thanks a lot for your help.
> > ![IMG_20210724_193117](https://user-images.githubusercontent.com/10421932/126870999-00d20443-048e-4f2b-937a-6a8d4b2b9d46.jpg)
> > ![IMG_20210724_193120](https://user-images.githubusercontent.com/10421932/126871004-7786813f-568d-470e-938e-12e29b68d2ea.jpg)
> > ![IMG_20210724_193122](https://user-images.githubusercontent.com/10421932/126871006-273d1dda-99c5-4d14-9d06-687ddf1586c2.jpg)
> > ![IMG_20210724_193112](https://user-images.githubusercontent.com/10421932/126871007-7d8270a8-8a52-48b4-9a82-cb45c633ef97.jpg)
> > ![IMG_20210724_193116](https://user-images.githubusercontent.com/10421932/126871009-3d81132a-e631-49b6-bb5c-e845abe68582.jpg)
> 
> Sir,
> Can you please post the the code link which you is working fine without any issue .So that I will correction my code according to your program
> 
> [Subashsaraf@gmail.com](mailto:Subashsaraf@gmail.com)


Sir,
     Can you please post the the code link which you is  working fine without any issue  .So that I will correction my code according to your program 

Subashsaraf@gmail.com

**Comment by 2BECKHAM2** [comment]
@subashsaraf 

Please check the example code at https://github.com/2BECKHAM2/ESP32-HUB75-MatrixPanel-I2S-DMA-Examples

**Comment by mrfaptastic** [comment]
Excellent work @2BECKHAM2 - Would you mind raising a pull request to this repository to update the SimpleTextShapes example to use the new pointer based usage of this library and mxconfig ?

**Comment by 2BECKHAM2** [comment]
Sure. Will do.

Thanks a lot.
