### ISSUE TITLE
Great job to you guys

### ISSUE THREAD

**Issue by Dcmwrnd** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#146]
This is a fantastic library. I’m using 12 pcs P4 panels (64 x 32 pixels). Did not expect this ESP32 is so powerful.
Thank you to all you guys. Below here are some video links using VirtualMatrixPanel library.

http://www.dcmw.com.my/video/ESP32-Hub75.mp4
http://www.dcmw.com.my/video/ESP32-Spectrum-12x64x32.mp4
http://www.dcmw.com.my/video/LedPanels.mp4

**Comment by mrfaptastic** [comment]
Thank you! I especially like 'ESP32-Hub75.mp4' - great selection of hot women. Probably the best use of this library so far.

You're actually driving **12** panels? That's amazing.

**Comment by Dcmwrnd** [comment]
Yes, I’m using 12 panels. Total pixels is 256 x 128. All the animated gif files are 256 x 128 and are stored in SD card because spiffs memory got not enough space. If I’m not mistaken I think I tested up to 14 panels & that’s the max I can go. 
![20210403_234302s](https://user-images.githubusercontent.com/87077282/124808684-cdbe8800-df91-11eb-9887-c83d527c5d18.jpg)
Try to go 15 panels the esp crash, saying memory not enough or something like that.

![20210409_211135s](https://user-images.githubusercontent.com/87077282/124808760-e6c73900-df91-11eb-9dad-8e4bf3a03e93.jpg)

**Comment by Dcmwrnd** [comment]
Sorry, quoted wrongly… total pixels is 256 x 96.
