### ISSUE TITLE
Accidentally commented code

### ISSUE THREAD

**Issue by tsctrl** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#172]
hi @mrfaptastic 

https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/blob/ab641b964272d121c5f7db6212324f5bfbd1650b/ESP32-HUB75-MatrixPanel-I2S-DMA.h#L418

https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/blob/ab641b964272d121c5f7db6212324f5bfbd1650b/ESP32-HUB75-MatrixPanel-I2S-DMA.h#L376
undefined reference to `MatrixPanel_I2S_DMA::shiftDriver(HUB75_I2S_CFG const&)'

https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/blob/ab641b964272d121c5f7db6212324f5bfbd1650b/ESP32-HUB75-MatrixPanel-I2S-DMA.cpp#L730
error: this 'if' clause does not guard... [-Werror=misleading-indentation]

look something not right there

**Comment by mrfaptastic** [comment]
I want to remove the legacy begin function so had commented it out, but have uncommented it for now.

**Comment by tsctrl** [comment]
also this issue @mrfaptastic ,

https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/blob/ab641b964272d121c5f7db6212324f5bfbd1650b/ESP32-HUB75-MatrixPanel-I2S-DMA.h#L376

undefined reference to `MatrixPanel_I2S_DMA::shiftDriver(HUB75_I2S_CFG const&)'

**Comment by tsctrl** [comment]
sorry the tittle a bit misleading

**Comment by tsctrl** [comment]
yup build with no issue, thanks @mrfaptastic
