### ISSUE TITLE
Build Error on invalid reference header

### ISSUE THREAD

**Issue by tsctrl** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#177]
Hi @mrfaptastic,

Build Error on invalid reference header:
https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/blob/482312b4a70652bb03d75b009e2896b669bb13fa/ESP32-VirtualMatrixPanel-I2S-DMA.h#L101

thanks!

**Comment by mrfaptastic** [comment]
2f8f465cc60fd863030be2acea462d0300c1cba3
