### ISSUE TITLE
Excel calculator possible error

### ISSUE THREAD

**Issue by ccoenen** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#189]
In the excel file, you're calculating the `Total Pixels` like this:
![grafik](https://user-images.githubusercontent.com/124909/135047033-441f3a32-6cb2-4206-9ddc-df54984adfa7.png)

I believe it should be <code>=B4\*<ins>B5</ins>\*B6</code> instead.

**Comment by vortigont** [comment]
Tnx, @ccoenen, you are right. I had 64*64 and obviously missed it :)
