### ISSUE TITLE
Led P5 outdoor drawPixel conflict position

### ISSUE THREAD

**Issue by macduyhai** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#201]
Code test:
  dma_display.setTextSize(1);     // size 1 == 8 pixels high
  dma_display.setTextWrap(false); // Don't wrap at end of line - will do ourselves

  dma_display.setCursor(0, 0);   // start at top left, with 8 pixel of spacing

  uint8_t w = 0;
  char *str = "ESP32 DMA 123456789123456789123456789123456789123456789123456789";
  Serial.println(strlen(str));
  for (w = 0; w < strlen(str); w++) {
    dma_display.setTextColor(dma_display.color565(255, 0, 255));
    dma_display.print(str[w]);

  }
  
  --> Start character start in (0,8) --> conflict position
  
  
  
![image](https://user-images.githubusercontent.com/25715092/139826512-8c1661d2-5650-4ee8-b26d-0c0f8a8ab7d8.png)

**Comment by mrfaptastic** [comment]
What's the actual issue?

**Comment by macduyhai** [comment]
Im setting cursor at pos (0,0) but when i run this code i see character begin at pos(0,8).
(0,0);(0,8) output the same

**Comment by macduyhai** [comment]
> What's the actual issue? Does a drawPixel (0,8) light up the correct LED?

drawPixel (0,0) light up the incorrect LED 
Code: dma_display.drawPixel(0, 0, dma_display.color444(15, 0, 0));
Look at this picture (draw a pixel ,red led) 

![image](https://user-images.githubusercontent.com/25715092/139839102-3c233924-c186-4770-b897-0dc69ed45cbc.png)

**Comment by macduyhai** [comment]
I run example testshapes_32x64 . Results showing errors
![image](https://user-images.githubusercontent.com/25715092/140010747-ca916646-ddf4-49d7-b659-b0e7b518239f.png)

**Comment by mrfaptastic** [comment]
Looks like a 1/8 scan panel right which isn't supported.

Post technical details of the panel as well as your full sketch. May need to use that other 1/8 scan example that hasn't been fully confirmed as working.

**Comment by macduyhai** [comment]
> Looks like a 1/8 scan panel right which isn't supported.
> 
> Post technical details of the panel as well as your full sketch. May need to use that other 1/8 scan example that hasn't been fully confirmed as working.

My panel :
Led maxtrix P5 full color outdoor 
IC : ICN2037BP
1/8 Scan

How  can I do for panel run correct  ? Thanks

**Comment by mrfaptastic** [comment]
Refer to and read: https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/issues/154

**Comment by mrfaptastic** [comment]
Try new example: https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/tree/master/examples/One_Eight_1_8_ScanPanel
