### ISSUE TITLE
Additional symbols

### ISSUE THREAD

**Issue by fruktiz32** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#210]
Hello, thanks for great library! I want to ask how I can add two glyphs to default font? Actually I need Euro and GBP symbols. And one more question is it possible to align text to left and to right or it is only way to do it with setCursot() fucntion? Thank you!

**Comment by mrfaptastic** [comment]
This is a question for the AdafruitGFX library I'm afraid.
