### ISSUE TITLE
The "AnimatedGIFPanel" example not working

### ISSUE THREAD

**Issue by CoalBob** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#227]
Hi, I slightly edited this example code for my home project. 
It's works fine when I uploaded the code/files to my ESP32 few weeks ago. But things goes wrong when I reupload the same stuff yesterday. 
I tested the original example code and nothing changed. And I got this warning when uploading, but not sure if this showed up before.

`D:\Arduino stuff\libraries\ESP32_HUB75_LED_MATRIX_PANEL_DMA_Display\examples\AnimatedGIFPanel\AnimatedGIFPanel.ino: In function 'void loop()':
D:\Arduino stuff\libraries\ESP32_HUB75_LED_MATRIX_PANEL_DMA_Display\examples\AnimatedGIFPanel\AnimatedGIFPanel.ino:258:15: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 char *szDir = "/gifs"; // play all GIFs in this directory on the SD card
               ^~~~~~~
`
The serial monitor shows like this. Seems the ShowGIF function didn't work
![image](https://user-images.githubusercontent.com/55158419/147112433-e3edf369-70e8-4e35-b50d-ec85e4a7f620.png)

Being pretty much a beginner so I just could not figure out what is going on, plz help

**Comment by mrfaptastic** [comment]
I've fixed this in the git. Some changes in another external library broke this example.

**Comment by CoalBob** [comment]
Thank you !
