### ISSUE TITLE
esp32_i2s_parallel_dma.h compiler warning

### ISSUE THREAD

**Issue by solhuebner** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#231]
In this snippet even if width is I2S_PARALLEL_WIDTH_8 it will return **2** if ESP32_ORIG is defined but port != I2S_NUM_1 as it will use 
case I2S_PARALLEL_WIDTH_16 instead:

```
static inline int i2s_parallel_get_memory_width(i2s_port_t port, i2s_parallel_cfg_bits_t width) {
  switch(width) {
    case I2S_PARALLEL_WIDTH_8:

#ifdef ESP32_ORIG	
      // IS21 supports space saving single byte 8 bit parallel access
      if(port == I2S_NUM_1) {
        return 1;
      }
#else 
	return 1;
#endif

    case I2S_PARALLEL_WIDTH_16:
      return 2;
    case I2S_PARALLEL_WIDTH_24:
      return 4;
    default:
      return -ESP_ERR_INVALID_ARG;
  }
}
```

Is that the intended behaviour?

If yes we might want to modify it to the following to make the compiler happy:

```
      if(port == I2S_NUM_1) {
        return 1;
      } else {
        return 2;
      }
```

**Comment by mrfaptastic** [comment]
> In this snippet even if width is I2S_PARALLEL_WIDTH_8 it will return **2** if ESP32_ORIG is defined but port != I2S_NUM_1 as it will use case I2S_PARALLEL_WIDTH_16 instead:

That's correct.
