### ISSUE TITLE
Scan issue

### ISSUE THREAD

**Issue by tsctrl** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#245]
hi @mrfaptastic , @vortigont 

this is not library issue. sorry as i am asking this here
i have issue on the scan lines pattern shown as below:

![20220113_224034](https://user-images.githubusercontent.com/75555993/149352033-ba2d8434-8779-41db-a585-cd04941e41c4.jpg)

could you guess what potential the culprit for this? is it a a,b,c,d lines might be not properly connected. or lat oe or clock issue or something else. 

your experience on this and suggestion to investigate are really appreciated.
thanks at the earliest!

**Comment by mrfaptastic** [comment]
Looks like an address line issue. I assume the image that you were trying to display looks fine for the lines that do show right?

**Comment by tsctrl** [comment]
yes, issue on horizontal lines

**Comment by tsctrl** [comment]
tested all address lines are all connected and have 1.6v from gpio

**Comment by mrfaptastic** [comment]
Yes. I mean abcde lines.

These panels are supposed to have 5v input. They work with 3.3v from the ESP 32 for a few chained panels... But 1.6? Way too low

**Comment by tsctrl** [comment]
yup, thats the reading i got from gpio on address pin referenced to main ground. i have fix the issue by replacing the esp32 mcu. not sure is a chip defect or bad soldering.

thanks @mrfap!
