### ISSUE TITLE
Support for SM5266P chip

### ISSUE THREAD

**Issue by Olejan** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#250]
I have an 80*40 panel (P4) with SM5266P chip. It could not be launched using the "ESP32-HUB75-MatrixPanel-I2S-DMA" library. This library mentions the SM5266P chip in the "HUB75_I2S_CFG" structure, but the "shiftDriver" function does not support this chip. Is it planned to support the SM5266P chip?

**Comment by solhuebner** [comment]
Have you tried: `mxconfig.driver = HUB75_I2S_CFG::SM5266P; `

And maybe also have a look at https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/issues/164
