### ISSUE TITLE
Q: Hardware setup for smart shield v0

### ISSUE THREAD

**Issue by porkyneal** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#260]
I have developed hardware based around the smartMatrix ESP32 smartshield V0 --> [Here](https://github.com/pixelmatix/SmartMatrix/blob/master/extras/hardware/ESP32/SmartLEDShield_ESP32_THT_V0_sch.pdf)

Is it possible to use this library with that hardware setup, (8 bit parallel?)

This is the pinout in smartMatrix:

```#define R1_PIN  GPIO_NUM_4
#define G1_PIN  GPIO_NUM_21
#define B1_PIN  GPIO_NUM_22
#define R2_PIN  GPIO_NUM_2
#define G2_PIN  GPIO_NUM_25
#define B2_PIN  GPIO_NUM_0

#define A_PIN   -1
#define B_PIN   -1
#define C_PIN   -1
#define D_PIN   -1
#define E_PIN   -1

#define LAT_PIN GPIO_NUM_27
#define OE_PIN  GPIO_NUM_32

#define CLK_PIN GPIO_NUM_26```

But this does not seem to work when I translate this into this library format.

Please close if the answer is no, thanks for your time.

**Comment by mrfaptastic** [comment]
This library does not have support for 8 bit parallel mode / use of external shift registers.
