### ISSUE TITLE
Function to transfer the whole pannel(s)?

### ISSUE THREAD

**Issue by zesinger** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#273]
Hello
Is there any fast function to transfer the whole matrix pannel(s) in one call? I have a full buffer filled with RBG values and would like to avoid the `for (j=...){for (i=...){dma_display->drawPixelRGB888(i,j,R,B,G);}}` if possible.
Thanks
David

**Comment by vortigont** [comment]
No, there is no such methods for now except fast functions to draw lines and rectangles.
I was thinking about creating exactly the thing you are asking for, but it's not that easy as it may seem. For one panel is not a problem, but for chained and combined panels it requires sophisticated transformation logic that ruins the whole idea.
Still this idea is my TODO list for future :) (do not have those RGB panels in possession for now)

**Comment by zesinger** [comment]
Thanks a lot for your answer.
Even x calls for x pannels could be great!

**Comment by board707** [comment]
>  it's not that easy as it may seem. For one panel is not a problem, but for chained and combined panels it requires sophisticated transformation

It is not difficult for directly chained panels and even for zigzag connections, no transformation required. I tryed to program fast functions for running text by shifting entire pixture to left or right.

**Comment by zesinger** [comment]
Thanks anyway for your great software.
