### ISSUE TITLE
Bars across the panel

### ISSUE THREAD

**Issue by markphelan** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#275]
This is what I get on all example sketches:
![image](https://user-images.githubusercontent.com/2466933/162395049-82111804-be18-4172-a5ff-a3c458dcc354.jpeg)

Just a 1/16 scan P5 64x32 panel from [PanelsRUs](https://panelsrus.co.uk/collections/panels/products/p5-64x32-indoor-led-panel)

Tried changing the latch blanking but it made no difference. Couldn't see any similar example of this behaviour in previous issues.

**Comment by DarrylStrong** [comment]
Looks like you don't have the 'D' row driver pin connected/configured correctly.

**Comment by markphelan** [comment]
You were absolutely spot-on, a dry joint on IO17 on my ESP32 module. Thank you!
