### ISSUE TITLE
How to increase the brightness

### ISSUE THREAD

**Issue by seoungbin0125** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#285]
Is there a way to increase the brightness?
It is dark even though it is raised to the maximum through the setPanelBrightness() function.
The left side of the picture below is the corresponding library, and the right side is the other library.
Please give me some advice.

![KakaoTalk_20220525_143727336](https://user-images.githubusercontent.com/67889670/170187887-194cd1cf-25bc-4da8-bad4-afcfd248540c.jpg)

**Comment by DarrylStrong** [comment]
What colour bit depth are the two libraries set to?

**Comment by seoungbin0125** [comment]
The color bit uses the color565 to 888 function.
I don't know what the hardware says
How can I set the color bit?
The other library is p3rgb

**Comment by DarrylStrong** [comment]
I was meaning the libary setting for output colour resolution. 

// 8bit per RGB color = 24 bit/per pixel,
// might be reduced to save DMA RAM
#ifndef PIXEL_COLOR_DEPTH_BITS
 #define PIXEL_COLOR_DEPTH_BITS      **8**
#endif
