### ISSUE TITLE
Inconsistent "B" port GPIO pin.

### ISSUE THREAD

**Issue by abrender** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#298]
In the [Wiring ESP32 with the LED Matrix Panel](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA) section, the pin mapping diagram maps "B -> IO19" ... while the code sketch under it has "#define B_PIN 22".

All the other pins in the code are consistent with the diagram, but the change in B_PIN is subtle and tripped me up when I just wanted to change E_PIN but copied that code and B_PIN changed too.

Thanks for checking on this!

**Comment by mrfaptastic** [comment]
Thanks. Updated README with https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/commit/efd64b68bb0117ebaa7986bc497197ce55541200
