### ISSUE TITLE
is this library compatible with 1/32 scan?

### ISSUE THREAD

**Issue by lols** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#303]
Hi, is it compatible with 1/32 scan panel do i need to set scan or the library default scan is 1/16?

for 2 panel one top one bottom
```
#define PANEL_RES_X 128
#define PANEL_RES_Y 64
#define NUM_ROWS 2 
#define NUM_COLS 1

#define SERPENT true
#define TOPDOWN false

virtualDisp = new VirtualMatrixPanel((*dma_display), NUM_ROWS, NUM_COLS, PANEL_RES_X, PANEL_RES_Y, SERPENT, TOPDOWN);

```
is this correct?
Thanks

**Comment by DarrylStrong** [comment]
You haven't defined PANEL_RES_Y.....

**Comment by lols** [comment]
ouch hahaha copy paste wrongly

**Comment by DarrylStrong** [comment]
I use the library to drive 384x64 1/32 displays. I don't use virtualmatrixpanel for this as it drives them natively. Due to the 64 pixel height it drives them at 1/32 automatically.

**Comment by dosipod** [comment]
I have used the code with p2 64x64 1/32 scan , look at the code here  https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/issues/288#issuecomment-1166697540
@DarrylStrong  could you please share your code for 384x64 ? I have 4 other panels but only used one  ,

**Comment by DarrylStrong** [comment]
I just set the panel res to 384x64 and one row/column.
Not easy to share my code as I have heavily modified the library from an older version.
Just make sure that you have all the output pins correctly allocated and the right driver chip selected.

**Comment by mrfaptastic** [comment]
@dosipod - Can I close this issue?
