### ISSUE TITLE
Problem with 64 x 64 display (striped images)

### ISSUE THREAD

**Issue by flasher69** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#309]
Hi guys,

I have big issues with the images shown on my HUB75 64 x 64 display. No matter which example I tried, I get the same results. The image shown on display is always striped in 4 sections. I've even tried to change some settings in ESP32-HUB75-MatrixPanel-I2S-DMA.h (such as MATRIX_WIDTH/HEIGHT) but the results always stay the same. I tried another panel from same brand and different ESP32 boards but always the same results.
Any idea what might be the problem?
Thank you for the help.
cheers

![1660327706573](https://user-images.githubusercontent.com/22278347/184620398-6cd870ef-4c1c-425e-bd4e-b9338559a35c.png)
.

**Comment by board707** [comment]
Do you connect a E pin?

**Comment by ergindemir** [comment]
Some examples modify e pin afterwards. 
Modify the following line if it's in your code:
`mxconfig.gpio.e = 18;`

**Comment by flasher69** [comment]
> 

Thanx a lot ergindemir. I've changed E-Pin in HUB75-MatrixPanel-I2S-DMA.h and scatches to pin 18 and now everything works :) Thank you for your help
