### ISSUE TITLE
Can I use 32x32 panels?

### ISSUE THREAD

**Issue by anilaras** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#310]
Hi, 
All provided examples used 64x32 panels. Can I use this library with 32x32 panels.

**Comment by mrfaptastic** [comment]
There's no reason you couldn't. 

BUT compatibility has little to do with the resolution of the panel and more to do with the *chip* used to drive the panel and take the digital signals from the esp32.

There are lots of different driver chips. It is luck in the end.
