### ISSUE TITLE
esp32 wifi ap is broken when i use 480x32 pixels

### ISSUE THREAD

**Issue by mzpbvsig** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#316]
really peculiar

**Comment by DarrylStrong** [comment]
Memory issues? Try dropping the colour depth.

**Comment by board707** [comment]
>  Try dropping the colour depth.

As far I understand the colour depth will be dropped automatically by library itself in case of memory shortage.

**Comment by mrfaptastic** [comment]
No, there is no automatic color depth changing.

**Comment by mrfaptastic** [comment]
> > Try dropping the colour depth.
> 
> As far I understand the colour depth should be dropped automatically by library itself in case of memory shortage.

Incorrect. There is no automatic changing of colour depth. You can only change this at compile time.

**Comment by mzpbvsig** [comment]
I chanage PIXEL_COLOR_DEPTH_BITS 3 is work well, but not sure is has other question.
