### ISSUE TITLE
Drawing in different orientations

### ISSUE THREAD

**Issue by VictorHofstede** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#40]
Hi everyone,

would it be possible to write text in different orentations? I have a 64x32 panel, but I would like to use it lengthwise and write text into it. So it would function as a 32x64 panel. Would this be possible and if so, how?

**Comment by csloz** [comment]
Yes.  

Just turn the panel sideways.

You can use Adafruit_GFX to display text in whatever orientation you feel like. 
It's that simple.

**Comment by VictorHofstede** [comment]
Hmm I tried using 
  dma_display.setRotation(rotation);
with rotation set to 0, 1, 2, 3 and no matter what parameter it did not change the orientation of the text I wrote.

Example:
` 
dma_display.begin(); // use default pins
dma_display.setRotation(3);

dma_display.setCursor(0, 0);
dma_display.println("Test line");
`
