### ISSUE TITLE
Display sometimes missing rows / random LEDs flickering

### ISSUE THREAD

**Issue by Vopchacik** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#492]
When using the double buffer example every 4th row is blank, and when nothing shows up in the row it is not black but a very faint red.
However when i use the Plasma example it shows properly when it shows the red - white fire looking plasma, when using the rainbow one random pixels start blinking.

The power supply im using is 5V 3A which should be enough to supply two 32x64 displays.

I use ESP32 S2 mini with a display using FM6126B drivers 32x64 2 in a row, its  set to FM6216A in the script. Because of using ESP32 S2 mini the pins are manually set to :
    #define R1_PIN 3
    #define G1_PIN 5
    #define B1_PIN 7
    #define R2_PIN 9
    #define G2_PIN 11
    #define B2_PIN 12
    #define A_PIN 13
    #define B_PIN 10
    #define C_PIN 8
    #define D_PIN 6
    #define E_PIN -1 
    #define LAT_PIN 2
    #define OE_PIN 1
    #define CLK_PIN 4

I tried to use  these commands:
  mxconfig.latch_blanking = 4/3/2/1;
  mxconfig.i2sspeed = HUB75_I2S_CFG::HZ_20M/8M;
  mxconfig.clkphase = true/false;

This didn't seem to do a single thing to the issue.
Same display did work properly on the PxMatrix library using ESP8266.

**Comment by mrfaptastic** [comment]
You opened this issue then closed it. What was the fix?

**Comment by Vopchacik** [comment]
It was a power supply issue, probably that it was unstable, it for sure had enough power to handle the display, not sure why it worked with 8266 tho.

> You opened this issue then closed it. What was the fix?
