### ISSUE TITLE
External RAM

### ISSUE THREAD

**Issue by dmb-220** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#55]
do you plan to implement PSRAM in the future?

there would be more opportunities.

or maybe it already works? just need to esp32 accordingly with PSRAM

**Comment by mrfaptastic** [comment]
ESP32's can't do DMA from PSRAM

**Comment by mrweaver** [comment]
Food for thought, regarding the [ESP-S3](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/external-ram.html):

> Note, although ESP32-S3 has hardware support for DMA to/from external RAM, this is not yet supported in ESP-IDF.
