### ISSUE TITLE
Any issue with AsyncWebServer and AsyncMQTT

### ISSUE THREAD

**Issue by hallard** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#56]
Until there I'm using PxMatrix, even if it's working fine, when added heavy stuff such as ayncWebServer or AsyncMQTT there are some issues (ESP32 crash), I'm thinking moving to this DMA version, but has anyone experienced better results and no issues with MQTT and or WebServer implemented on the same time ?

Thanks

**Comment by mrfaptastic** [comment]
Shouldn't be any issues.

**Comment by hallard** [comment]
Confirmed, compiled, uploaded, works fine, no crash no flicker, with both combined async libraries even with OTA

Thanks for this awesome lib.

**Comment by mrfaptastic** [comment]
Hi @hallard. Thanks for providing follow-up feedback!

Any chance you could also test with the dev branch as well? We're going to roll this out at some point in the future.

**Comment by hallard** [comment]
Ha ha didn't even took time to see existence of this branch, for sure, I will use it instead.

**Comment by hallard** [comment]
Hi @mrfaptastic,

just tested the dev branch, so far, so good on my side.

Just one thing, looks like missing `setfastmode()` on dev branch :-).

**Comment by vortigont** [comment]
@hallard, setfastmode() is deprecated in dev, it is always 'fast' now :)
