### ISSUE TITLE
random pixel issue 

### ISSUE THREAD

**Issue by tsctrl** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#69]
Hi @mrfaptastic ,

I am using dev branch to test the led using the double buffer example with 6 panel virtual matrix. i am getting additional fixed pixel display in several part of the panel as shown in image below:

![Inked20210122_100643_LI](https://user-images.githubusercontent.com/75555993/105438611-4ceb2880-5c9e-11eb-9a4b-5e10f783adb7.jpg)

i confirm this issue as comparison output from the master branch. 
1. the circle image are exist on both master and dev branch. only visible on 3rd and 6th panel on 6 chained panel.
2. the arrow are shifted pixel on every panel. is 10 pixel shift to be exact.

the dev config are default SHIFT HZ_10M 255 brightness and MinRefreshRate 100. 
changing refresh rate/ brightness/i2s freq/shift does not fix the issue.

chained panel are set to 1 row 1 panel config

**Comment by mrfaptastic** [comment]
Can you also test with the earlier version of this library. v 1.0.2

There's no virtual panel class with this release, but you can still use it to test for artifacts. Just out of curiosity, what are you building with a 6 x 64px panel?

**Comment by tsctrl** [comment]
Hi @mrfaptastic 

i have switching branch for this test to confirm. issue no 2 gone when using release v1.0.2 with no virtual panel. i just open the buffer_swap_test example. change the port and run. however still seeing issue no 1 but lesser. 
![20210123_013552_LI-RESULT](https://user-images.githubusercontent.com/75555993/105526108-ebb66a00-5d1c-11eb-923c-b5b0c136eee5.jpg)
top: image on the v1.0.2. only visible in 3rd and 6th panel.

My finding lowering the current would hide the visible issue in no 1 for library in dev branch and master branch but not in the v1.0.2. lowering current in v1.0.2 does not impacting the display. i am using 30A bench power supply. 

![20210123_015432-LOWER-CURRENT](https://user-images.githubusercontent.com/75555993/105527178-51efbc80-5d1e-11eb-8bf8-fed3194b6acf.jpg)
top: clean display on lower current for dev and master branch

![Inked20210123_015444-FULLPOWER_LI](https://user-images.githubusercontent.com/75555993/105527762-14d7fa00-5d1f-11eb-9d3b-49e27a5f2578.jpg)
top: Issue 1. display on max current for master branch as stated in the initial comment. only visible in 3rd and 6th panel.

No issue if using single panel. let me try with fixed led power supply 40A and share the result later. i am building a notification board btw.

Thanks!

**Comment by tsctrl** [comment]
I have switched to 4x4 panel. issue with panel no 3 done but still having artifacts in the last panel. Not sure if this is wiring/psu or a dupon issue.

Thanks!

**Comment by vortigont** [comment]
You might try latest dev, there is a new method MatrixPanel_I2S_DMA::setLatBlanking(uint8_t v) to control the number of clocks output is disabled before/after LAT signal. May help with ghosting in some cases. Value coud be set between 1 (default) to 4.

**Comment by tsctrl** [comment]
Hi @vortigont, thank you so much on the fixes.
The ghosting issue no 2. was fixed! thank you. but not able to see any difference when changing LatBlanking for 1 to 4 (bit dimmer in 4).

however issue 1. which showing random pixel in panel 3 and 6 for 6 panel, and panel 4 for 4 panel config still exist but not as bad as before. still 3 dots in panel 3 and quite a lot in panel 6 for 6 panel config. have used 60A power supply. still the same. but i am ok with it. probably issue with my dupon or because i am using 3 different panel in a chain or because i am using 1.5m idc cables. @mrfaptastic is this is as expected? are you able to replicate the issue on you end?

![Inked20210130_202251-123_LI](https://user-images.githubusercontent.com/75555993/106356372-15354e00-633a-11eb-93da-56557d2d86c3.jpg)
3 dots in panel 3.

thank you @mrfaptastic , @vortigont

**Comment by tsctrl** [comment]
i am using DoubleBufferSwap.ino and add chained panel codes from ChainedPanels.ino. with 1 NUM_ROWS and 1 NUM_COLS to replicate the issue.

**Comment by mrfaptastic** [comment]
Do you have any capacitors on each panel? You need to have at least 2000uf caps across VCC and GND on each panel to reduce noice which can cause artifacts.

**Comment by tsctrl** [comment]
Did not have at the moment.

**Comment by vortigont** [comment]
> i am using DoubleBufferSwap.ino and add chained panel codes from ChainedPanels.ino. with 1 NUM_ROWS and 1 NUM_COLS to replicate the issue.

I'm quite confused, Why are you using 1x1 configuration if you have 6 or 4 panels? Anyway it looks more like some hardware/interference issue.
LatBlanking might or might not help for some corner cases, just thought it'd better have this knob available to try than hardcode some constant value.

**Comment by tsctrl** [comment]
using 1x1 configuration to draw the same pattern for all panels just to do the test. although i having same issue when not using virtual panel with 3x2 panel connected. i will swap all with same panel and recheck all pin configuration again.

**Comment by tsctrl** [comment]
I have tested using different hardware and the display work in the master and dev branch with no false pixel. Closing this one

thank you.

**Comment by vortigont** [comment]
@tsctrl awesome! would appreciate if you could share some details what was the issue - cabling, power, panel ordering?
