### ISSUE TITLE
Compiling under PIO / PlatformIO

### ISSUE THREAD

**Issue by anthonyjclarke** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#82]
Not strictly an issue, but wonder if anyone can help me as I am trying to use PIO.

Using the Sample Chain Panels Sketch, it receive the following error,

"'HUB75_I2S_CFG' was not declared in this scope"

![image](https://user-images.githubusercontent.com/9491428/107888580-5b58f700-6f61-11eb-8d09-e898d3164ce4.png)

![image](https://user-images.githubusercontent.com/9491428/107888589-70ce2100-6f61-11eb-8f72-15e15861d801.png)

Appreciate any guidance!

**Comment by vortigont** [comment]
You can take a look at this [example](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/tree/master/examples/PIO_TestPatterns)
