### ISSUE TITLE
Cloned lines issue

### ISSUE THREAD

**Issue by radical-las** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#83]
When drawing any image on led panel it draws "cloned" lines. I made a little sketch, that should fill display line by line and writes to console number of line, that is drawing right now. I don't relly know what's wrong.
[link to sketch](https://pastebin.com/zvUZfdkx)
[link to video how it works](https://youtu.be/AMCZxoxgggA)

PS: my panel uses rul5358 (SHIFTREG_ABC_BIN_DE) decoder

**Comment by mrfaptastic** [comment]
Can you try an older version of this library ? 1.0.2  and see if this issue persists?

**Comment by radical-las** [comment]
> 
> 
> Can you try an older version of this library ? 1.0.2 and see if this issue persists?

Yep, issue still persists.

**Comment by mrfaptastic** [comment]
You'll need to use pxMatrix library sadly.

**Comment by mrfaptastic** [comment]
> PS: my panel uses rul5358 (SHIFTREG_ABC_BIN_DE) decoder

You will need to use PxMatrix which supports this type of panel.

**Comment by radical-las** [comment]
> 
> 
> You'll need to use pxMatrix library.

PxMatrix library should support my panel, but it uses very odd cabling
