### ISSUE TITLE
Query to get current panel brightness

### ISSUE THREAD

**Issue by tsctrl** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#89]
Hi @mrfaptastic ,

i have one queries to get current panel brightness function. by having this. we could get current panel brightness so attempt to update the brightness can only be done only if the current brightness value are different than the panel brightness else every time the loop run setBrightness8(value) will always get executed.

is it ok to update the panel brightness with the same value like in every 5 second loops? any impact? 

thank you

**Comment by mrfaptastic** [comment]
Hi @tsctrl. I suggest having a variable within your code to keep track of the last value set to the library.

Trial and error is the best way to see if frequent changing of brightness values causes issues.
