### ISSUE TITLE
Problem to generate bitmap

### ISSUE THREAD

**Issue by tsctrl** [mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA#97]
Hi @mrfaptastic 

I have issue to generate bytes images. I am not able to get proper display for my own bytes generated from custom drawing bitmap. Weather icons bitmap in the example works great. but if i create 32x32px box for example. the box display in the panel  will split to 2 drawing.  the first half of the box will split and inverse and the and the half are displayed from the first pixel in the led panels. let say i draw a [ ] the result is ] [

wondering what is the proper settings to generate the bitmap. only change to monochrome? how about the main, line scan, trailing bits? do you use custom script to generate the bytes? i think it should be related to ordering or need to use custom script.

thank you.

**Comment by tsctrl** [comment]
one more, do we have to use the bitRead and the loop to render the image? no existing gfc function that can do this automatically?

**Comment by mrfaptastic** [comment]
I'm confused as to the issue? Is it an issue with the example? i.e. How to generate a bitmap for the example?

**Comment by tsctrl** [comment]
yes, how to generate the PROGMEM bitmap for the example. the normal bitmap which working with drawBitmap not working with the example.
how to create bitmap for the drawXbm565 monochrome or color?
how to utilize the drawXbm565 example and how to use drawXbm565 with bitmap with color information..

thank you @mrfaptastic

**Comment by mrfaptastic** [comment]
Updated instructions: https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/tree/master/examples/BitmapIcons

You can only draw a bitmap of a single colour. You will need to come up with your own solution if you want to draw full-colour images. Use: https://github.com/bitbank2/JPEGDEC or something.
